name: Build SeePackets
on:
  push:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B build

      - name: Build
        run: cmake --build build
